version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "commit2act"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1v8wohatxc38e"
s3_prefix = "commit2act"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_NAMED_IAM"
parameter_overrides = "ProjectName=\"commit2act\" EnvironmentName=\"dev\" DBName=\"sys\" DBUser=\"admin\" DBPassword=\"yayILoveCommittwoAct\" DBInstanceClass=\"db.t4g.large\" DBEngineVersion=\"5.7.mysql_aurora.2.09.2\" DeletionProtection=\"True\" EncryptDatabase=\"True\" CloudFrontPriceClass=\"PriceClass_100\" MinConfidenceThreshold=\"70\" CognitoAdminName=\"Matthew\" CognitoAdminEmail=\"stefan5@mail.ubc.ca\""
image_repositories = []
