version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "commit2actlive"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1ofs2gcz3cgz6"
s3_prefix = "commit2actlive"
region = "us-east-1"
capabilities = "CAPABILITY_NAMED_IAM"
parameter_overrides = "ProjectName=\"commit2act\" EnvironmentName=\"live\" DBName=\"sys\" DBUser=\"{fillIN}\" DBPassword=\"{fillIN}\" DBInstanceClass=\"db.t4g.medium\" DBEngineVersion=\"5.7.mysql_aurora.2.11.1\" DeletionProtection=\"True\" EncryptDatabase=\"True\" CloudFrontPriceClass=\"PriceClass_100\" MinConfidenceThreshold=\"70\" CognitoAdminName=\"mfurdyk\" CognitoAdminEmail=\"mfurdyk@takingitglobal.org\""
image_repositories = []
